# Generated by Django 2.0.9 on 2018-12-15 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=True, verbose_name='Ответ кандидата')),
            ],
            options={
                'verbose_name_plural': 'Ответы кандидата',
                'verbose_name': 'Ответ кандидата',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя кандидата')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почтв кандидата')),
            ],
            options={
                'verbose_name_plural': 'Кандидаты',
                'verbose_name': 'Кандидат',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name_plural': 'Испытания',
                'verbose_name': 'Испытание',
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наимнование планеты')),
            ],
            options={
                'verbose_name_plural': 'Планеты',
                'verbose_name': 'Планета',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=255, verbose_name='Вопрос для кандидата')),
                ('checked', models.BooleanField(default=True, verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
                'verbose_name': 'Вопрос',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя джедая')),
                ('planet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_planet', to='new_app.Planet', verbose_name='Джедай планеты')),
            ],
            options={
                'verbose_name_plural': 'Джедаи',
                'verbose_name': 'Джедай',
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='orden', to='new_app.Planet', verbose_name='Орден'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='question',
            field=models.ManyToManyField(blank=True, related_name='challenge', to='new_app.Question', verbose_name='Воспросы'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='planet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_planet', to='new_app.Planet', verbose_name='Кандидат планеты'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_cand', to='new_app.Teacher', verbose_name='Джедай планеты'),
        ),
        migrations.AddField(
            model_name='answer',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_answer', to='new_app.Candidate', verbose_name='Ответ кандидата'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_question', to='new_app.Question', verbose_name='Вопрос для кандидата'),
        ),
    ]
