# Generated by Django 2.0.9 on 2018-12-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_auto_20181216_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование планеты'),
        ),
    ]
