# Generated by Django 2.0.9 on 2018-12-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_auto_20181216_0701'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
            ],
        ),
    ]
